export const ACCELERATION = 0.5
export const JUMP_ACCELERATION = 6
export const RUN_ACCELERATION = 0.3
export const FLY_ACCELERATION = RUN_ACCELERATION / 2
export const VELOCITY_LOSS = 10
export const GRAVITY = ACCELERATION / 2
export const GROUND_FRICTION = ACCELERATION / 2
export const AIR_FRICTION = GROUND_FRICTION / 2
export const PLAYER_WIDTH = 20
export const PLAYER_HEIGHT = 30
