const constants = {
    ACCELERATION: 0.3,
    JUMP_ACCELERATION: 3,
    RUN_ACCELERATION: 0.1,
    VELOCITY_LOSS: 10,
    PLANET_MASS: 400000,
    PLAYER_WIDTH: 20,
    PLAYER_HEIGHT: 30,
    PLATFORM_SIDE: 40,
    SPEED_LIMIT: 10,
    DOWN_CONSTANT: 0.1,

    POINTS: 20000,
    BACKGROUND_RADIUS: 4000,
    LEVEL_RADIUS: 4000,
    PLANET_RADIUS: 3000,
    PLATFORMS: 1000,
    CAMERA_INERTIA: 20,

    TOUCH_DEBOUNCE_LIMIT: 10,
}

constants.FLY_ACCELERATION = constants.RUN_ACCELERATION / 2
constants.GROUND_FRICTION = constants.RUN_ACCELERATION / 2
constants.AIR_FRICTION = constants.GROUND_FRICTION / 2

export default constants
